### ISSUE TITLE
Fast one liner to replace the plugin.

### ISSUE THREAD

**Issue by Otto42** [raffjones/chrome-admin-menu-fix#4]
Loading a separate file and an HTTP roundtrip is slightly overkill. Also, the JS could be much simpler.

This seems to do the job for me. 

```
 if ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Chrome/45' ) !== false ) add_action('admin_head', create_function('', "echo \"<script type='text/javascript'>jQuery(window).load(function(){jQuery('#adminmenuwrap').hide().show(0);});</script>\";") );
```

**Comment by raffjones** [comment]
That's all good. 

Like I said it was just a quick fix to get something going a couple of weeks ago.

If you don't mind, stick it in a pull request and I'll merge it.

**Comment by codewithfeeling** [comment]
I like the idea of inline JS and will add that with a credit to you in the comments, but prefer to run the actions according to WordPress best practice - ie. to check server on admin_init, enqueue jQuery, and print the script in the footer. I've updated the script to drop the JS file load and co-credited you as author.
