### ISSUE TITLE
Version 1.1 doesn't work on WP4.3

### ISSUE THREAD

**Issue by ykato** [raffjones/chrome-admin-menu-fix#5]
Version 1.1 doesn't work 
I replaced the inline script with ver 1.0, then the menu corruption has been fixed.

p.s. I'm sorry that I've written incorrect information at first.

**Comment by codewithfeeling** [comment]
I just updated the code slightly to introduce a very short duration to the show method - can you try that? It's working fine on WP4.3 here although as you say, the version with no duration or zero duration was failing.

**Comment by ykato** [comment]
Thank you! It' works on my environment.

**Comment by codewithfeeling** [comment]
Great. Hopefully Google will fix it soon so we won't need this!

**Comment by danahis** [comment]
Could you please use <?php instead of a short open tag <? at line 39?
in some environment, the short open tag is disabled.
