### ISSUE TITLE
Please avoid PHP Short Open Tag <? at line 35: 

### ISSUE THREAD

**Issue by danahis** [raffjones/chrome-admin-menu-fix#6]
Thank you for the quick fix. I confirmed the latest fix does work in my enviroment.

But I needed make a small change at line 35  <? to <?php

PHP with short open tag disabled cuases: Parse error: syntax error, unexpected end of file in .... wp-content\plugins\chrome-admin-menu-fix-master\chrome-admin-menu-fix.php on line 39

Thanks,

**Comment by codewithfeeling** [comment]
Done.
